name: Compilation Multi-Plateforme

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # On lance 3 machines virtuelles en même temps : Linux, Mac et Windows !
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installer les dépendances et PyInstaller
      run: |
        pip install PySide6 pynput pyinstaller

    # Compilation conditionnelle selon le système d'exploitation pour inclure les bons composants de pynput
    - name: Compiler l'application (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        pyinstaller --onefile --noconsole --hidden-import="pynput.keyboard._win32" --hidden-import="pynput.mouse._win32" helper.py

    - name: Compiler l'application (Mac)
      if: matrix.os == 'macos-latest'
      run: |
        pyinstaller --onefile --noconsole --hidden-import="pynput.keyboard._darwin" --hidden-import="pynput.mouse._darwin" helper.py

    - name: Compiler l'application (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        pyinstaller --onefile --noconsole --hidden-import="pynput.keyboard._xorg" --hidden-import="pynput.mouse._xorg" helper.py

    - name: Sauvegarder le fichier compilé
      uses: actions/upload-artifact@v4
      with:
        name: MudaeHelper-${{ matrix.os }}
        path: dist/
